debug: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
spring:
  application:
    name: webapp


