server:
  port: 9999
  context-path: /uaa

security:
  sessions: if-required
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/alan-oauth?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: auth
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
