server:
  port: 9001
  context-path: /resource

security:
  sessions: NEVER
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/alan-oauth?characterEncoding=UTF-8
    username: uaa
    password: password
    driver-class-name: com.mysql.jdbc.Driver