logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN
    
server:
  port: 8080
spring:
  aop:
    proxy-target-class: true
  application:
    name: gateway

zuul:  
  routes:    
    startpage:
      path: /**
      serviceId: WEBAPP
    resource:      
      path: /resource/**
      url: http://localhost:9001/resource
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
  redis:
    cache-time: 30000


security:
  oauth2:    
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: ui1
      clientSecret: ui1-secret   
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/ # 指定注册中⼼的地址
