---
spring:
  profiles: peer1   # 指定profile=peer1
  application:
    name: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1 # 指定当profile=peer1时，主机名
  appname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/ # 将⾃⼰注册到peer2这个Eureka上⾯去
---
spring:
  profiles: peer2
  application:
    name: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  appname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/ # 将⾃⼰注册到peer2这个Eureka上⾯去