server:
  port: 8020
spring:
  application:
    name: feign-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/ # 指定注册中⼼的地址
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，⽽是使⽤静态配置的服务列表。静态服务列表可使⽤：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka