server:
  port: 8011
spring:
  application:
    name: ribbon-hystrix-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/ # 指定注册中⼼的地址
  instance:
    preferIpAddress: true