server:
  port: 8000
spring:
  application:
    name: provider-user # 项⽬名称尽量⽤⼩写
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:schema.sql # 指定h2数据库的建表脚本
    url: jdbc:mysql://localhost/learning?useUnicode=true&amp;characterEncoding=utf-8
    data: classpath:data.sql
    initialize: true
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/ # 指定注册中⼼的地址
  instance:
    preferIpAddress: true