server:
  port: 8000
spring:
  application:
    name: provider-user # 项⽬名称尽量⽤⼩写
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  datasource:
    username: sa
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql # 指定h2数据库的建表脚本
    url: jdbc:h2:~/test
    data: classpath:data.sql
    initialize: true
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/ # 指定注册中⼼的地址
  instance:
    preferIpAddress: true